name       : kwrited
version    : 5.23.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.0/kwrited-5.23.0.tar.xz : 65a74b5d6fb75f4129b528a8cec6e3aadcbccdee6f7e0bf2d994fb1854999ffb
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
