name       : kwrited
version    : 5.14.3
release    : 26
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.3/kwrited-5.14.3.tar.xz : f066fa274b2b5e19f8a4a1e95c283e263b592e58a365210cb11ba7a55dccebd3
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
