name       : kwrited
version    : 5.13.5
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/kwrited-5.13.5.tar.xz : caabc136af8bede8232484a23da7bd9d06f4121813f725b2d02fb24da6841694
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
