name       : kwrited
version    : 5.17.3
release    : 41
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.3/kwrited-5.17.3.tar.xz : 343d51d01dfde4a837492d67a3d8aa13411c2d47f51f89fa34edde1dd0d696d2
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
