name       : kwrited
version    : 5.12.5
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.5/kwrited-5.12.5.tar.xz : bf2ee7d7938c675bd485953bfe2ded9a824b391b26d2a8139d8f6fc2499e746f
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
