name       : kwrited
version    : 5.11.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/kwrited-5.11.1.tar.xz : 40b2f195cac34ff7380bdd1ac635fd55079f86fb8d8814a0b2013ca0e56dc287
license    : GPL-2.0
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
