name       : kwrited
version    : 5.16.1
release    : 34
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kwrited-5.16.1.tar.xz : 492db456650545101b8ecf1426cf31647ebf1b119af9dd05684ea902861f92f3
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
