name       : kwrited
version    : 5.16.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/kwrited-5.16.0.tar.xz : 26561775a280f326b7323170d6466d39447d98d0d5f593e7aaea5a62ef001559
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
