name       : kwrited
version    : 5.13.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.1/kwrited-5.13.1.tar.xz : 02e8ab740f4840357644314681c550f77f7f27ae64df8e36bd45bc123b20cf51
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
