name       : kwrited
version    : 5.10.5
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.5/kwrited-5.10.5.tar.xz : 894d7f3231e8842676560a5a1e872532e2c70dd302f647e7a2676143c982f072
license    : GPL-2.0
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
