name       : kwrited
version    : 5.15.4
release    : 31
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.4/kwrited-5.15.4.tar.xz : 7c25ed48ce85294ab4d5e3d4ffaaf3dd408f2a97cbb253b9adc9d5b8004db3c4
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
