name       : kwrited
version    : 5.20.5
release    : 58
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/kwrited-5.20.5.tar.xz : bfb2bb88e6b4e49a69b5c90b4688f3aba3b8e6771221e7c9332293bfc05a1bc0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
