name       : kwrited
version    : 5.27.5
release    : 85
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/kwrited-5.27.5.tar.xz : f2baec5827a87c035a116795615f2dba51ebaaab6297cbe8adf50410865fcc91
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
