name       : kwrited
version    : 5.19.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/kwrited-5.19.2.tar.xz : ea7326d6f726c8bbf1be1b04866587d46f51db01fe60e0bb4bda513b82c38f97
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
