name       : kwrited
version    : 5.13.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.3/kwrited-5.13.3.tar.xz : 59e6781dcf5689dfb4144876d609c24c3b4249fef17419cb7c38e0f62f8314d9
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
