name       : kwrited
version    : 5.21.2
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.2/kwrited-5.21.2.tar.xz : afed5c80700cfae4db18b22ddfdefeaaf72fe21f85188b2003b691dc94a211d0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
