name       : kwrited
version    : 5.16.5
release    : 38
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/kwrited-5.16.5.tar.xz : 4b122099b0a362fc409b50b7523689ba8a112508dad26f58753c6b648e7c5313
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
