name       : kwrited
version    : 5.14.5
release    : 28
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.5/kwrited-5.14.5.tar.xz : d06283cdfdb6ab1323e45a8e36b8bf119ffba523bc138ee081a4289499c62504
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
