name       : kwrited
version    : 5.21.5
release    : 64
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/kwrited-5.21.5.tar.xz : e1e79046b9657defa5074e46f7bcb09e9000f6e4bc3504eda9363fc60891294e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
