name       : kwrited
version    : 5.23.3
release    : 72
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.3/kwrited-5.23.3.tar.xz : 8498568bee3e2ea4006f7359a382bb4f1ad5a7359fe5dccdd100cf6695d7a604
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
