name       : kwrited
version    : 5.22.5
release    : 68
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/kwrited-5.22.5.tar.xz : 63bd95099452951dba9e10a5ba15c4b6693cc44fb3ce99b7cb45638890748e09
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
