name       : kwrited
version    : 5.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/kwrited-5.12.0.tar.xz : 385e8a9f2099856527686a418f11905a78705f20764f6dd9f7fa0f5065dc822b
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
