name       : kwrited
version    : 5.27.6
release    : 86
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.6/kwrited-5.27.6.tar.xz : 0665240812594b9c5ec20b24dde1734bedc33f1440eb8591e72429ab2b1a7894
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
