name       : kwrited
version    : 5.23.4
release    : 73
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.4/kwrited-5.23.4.tar.xz : 337adb66bb3c847442127b4ab2aa330b40476207024978c096219658e6ea5197
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
