name       : kwrited
version    : 5.20.1
release    : 54
source     :
    - https://download.kde.org/stable/plasma/5.20.1/kwrited-5.20.1.tar.xz : 444dd8b76dd67428bef0a25ef24e2eb4b445f6f8787a88063c48d64f9ab120f8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
