name       : kwrited
version    : 5.22.4
release    : 67
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.4/kwrited-5.22.4.tar.xz : 9158fb7dc963e01c356cf5572910d72e2914a749e3dd46956898a35d1c5e73e5
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
optimize   : lto
builddeps  :
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
