name       : kwrited
version    : 5.19.4
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.4/kwrited-5.19.4.tar.xz : 3f64acb63ce009c849ca3a49288795e20a894afc6fc77a0e2480ab294cce8272
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
