name       : kwrited
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/kwrited-5.9.5.tar.xz : aaad41bf140717f8bfa87381de9e1baad639afc30e06566a238f58767bd4ecea
license    : GPL-2.0
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - knotifications-devel
    - kpty-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
